# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

killrchat.security.rememberme.key: KillrChat

cassandra.test.clean.files: false

cassandra:
    host: localhost
    cql.port: 9042

